name: FreeBSD

on:
    push:
        branches: '*'
    pull_request:
        branches: '*'

jobs:
  perl-job:
    runs-on: macos-10.15
    name: FreeBSD Perl ${{matrix.perl}}
    strategy:
      fail-fast: false
      matrix:
        perl: [ '5.32' ]
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: Test in FreeBSD
      id: test
      uses: vmactions/freebsd-vm@v0.2.9
      with:
        usesh: true
        prepare: pkg install -y lang/perl${{matrix.perl}} p5-App-cpanminus
        run: |
          freebsd-version
          env ASSUME_ALWAYS_YES=YES pkg install -y git cmake-core ninja xorgproto libX11 libXrandr
          env ASSUME_ALWAYS_YES=YES pkg install -y flac libogg libvorbis freetype2 openal-soft libglvnd
          env ASSUME_ALWAYS_YES=YES pkg install -y libXcursor
          perl -V
          cpanm --installdeps -v -n --mirror http://cpan.cpantesters.org/ .
          cpanm -v --test-only .
